services:
  postgres:
    container_name: postgres_traffic
    image: postgres
    environment:
      POSTGRES_DB: "traffic_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - aspnet-https:/root/.aspnet/https:ro
    ports:
      - "5433:5432"

volumes:
  postgres-data:
  aspnet-https: